### ISSUE TITLE
Calender on website autoselects current day

### ISSUE THREAD

**Issue by jwestenhoff** [fsi-hska/iwi-website#66] opened 2021-04-21 14:21 UTC
Currently the calender on the home page of the website does not refer the current day.

To Reproduce:
- open the homepage https://iwi-hka.de/
- scroll to the calender

Actual:
- calender shows events of some day
- click on the current day
- calender shows events of current day

Expected:
- calender shows events of current day

It is the 21th april 2021 and this day is marked like there is an event on this day.
But it is not shown directly
![image](https://user-images.githubusercontent.com/61432429/115568187-59dae080-a2bc-11eb-8699-74e606c81102.png)

**Comment by SimonKienzler** [comment] 2021-04-21 14:24
Duplicate of #56

**Closed by SimonKienzler** 2021-04-21 14:24 UTC
Labels: enhancement

**Comment by jwestenhoff** [comment] 2021-04-21 14:26
thx @SimonKienzler :)
